[workspace]
members = ["libraries/*", "programs/*"]
resolver = "2"

[workspace.dependencies]
anchor-lang = "1.0.0"
anyhow = "1.0"
jupiter-amm-interface = { version = ">=1.0.0-beta.0, <2" }
rust_decimal = "1.26.1"
solana-program = "4.0.0"
solana-pubkey = "3.0.0"
spl-token-interface = "2.0.0"
spl-associated-token-account-interface = "2.0.0"
num-traits = "0.2"
thiserror = "1.0"
typenum = "1.17.0"
fixed = "1.11.0"
